### ISSUE TITLE
Rewrite rules flushed after upgrade, breaks some permalinks

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-kb-articles#107] opened 2015-04-23 18:00 UTC
@raamdev writes...
> When I visit this new KB Article (http://zencache.com/kb-article/how-do-i-setup-static-cdn-filters-with-keycdn/) and click the Static CDN Filters tag at the top of the article, the link it leads to is broken: http://zencache.com/kb/kb-tag/static-cdn-filters/

@jaswsinc writes...
> I updated the permalink settings to correct this. Something funky going on with this. I've seen that happen after the WPKBA plugin version is bumped, which causes a flush of WP rewrite rules. Not sure if this is a WP core bug, or something in our updater.
>
> It's working at ZenCache.com now, but we need to run some tests against a WPKBA upgrade to pinpoint this.

**Comment by jaswsinc** [comment] 2015-04-23 21:31
Thank you. I'm marking this as "ready for work" so that I can be reminded in OmniFocus that I need to research this. I'd say that anything with a "needs research" tag could also get the "ready for work" tag too. Agree?

**Comment by raamdev** [comment] 2015-04-23 22:42
> I'd say that anything with a "needs research" tag could also get the "ready for work" tag too. Agree?

I replied here: https://github.com/websharks/team/issues/28

**Comment by jaswsinc** [comment] 2015-06-08 02:40
I believe this has been resolved. Let's keep our eyes open though please :eyes: 

I think the problem here is that WPKBA was _not_ flushing rewrite rules on upgrade (like I thought it was), it only occurred during the initial activation. So any changes later were creating problems. Still not completely sure if this will resolve this issue, but I was unable to reproduce it after this change.

**Closed by jaswsinc** 2015-06-08 02:40 UTC
Labels: bug, needs research, ready for work
